# This is a basic workflow that is manually triggered

name: policingnetworkcosmos

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.


jobs:
  mac-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetos: [windows, darwin]
    name: policingnetworkcosmos for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}

      - name: Compile
        run: |
          cd cmd/policing-network-cosmosd
          go build .
          cd ..
          cd policing-network-cosmoscli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: policingnetworkcosmoscli ${{ matrix.targetos }}
          path: cmd/policingnetworkcosmoscli/policingnetworkcosmoscli

      - uses: actions/upload-artifact@v2
        with:
          name: policingnetworkcosmosd ${{ matrix.targetos }}
          path: cmd/policingnetworkcosmosd/policingnetworkcosmosd

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv64, amd64]

    name: policingnetworkcosmos for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          cd cmd/policing-network-cosmosd
          go build .
          cd ..
          cd policing-network-cosmoscli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: policingnetworkcosmoscli ${{ matrix.arch }}
          path: cmd/policingnetworkcosmoscli/policingnetworkcosmoscli

      - uses: actions/upload-artifact@v2
        with:
          name: policingnetworkcosmosd ${{ matrix.arch }}
          path: cmd/policingnetworkcosmosd/policingnetworkcosmosd
